os: linux
dist: focal

language: java
jdk:
  -openjdk11

addons:
  mariadb: '10.5'

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo mysql -u root --password="" < src/test/resources/META-INF.scripts/carrentaltest_user_schema_creation.sql
  - sudo mysql -u root --password="" < src/test/resources/META-INF.scripts/carrentaltest_table_creation.sql