os: linux
dist: focal
language: java
jdk: "-openjdk11"

addons:
  sonarcloud:
    organization: "reggy93"
#    Not needed since SONAR_TOKEN added to Travis CI variables
#    token:
#      secure: "$SONAR_TOKEN"
  mariadb: '10.5'

cache:
  directories:
    - "$HOME/.m2"
before_install:
  - git fetch origin master
  - sudo mysql -u root --password="" < src/test/resources/META-INF.scripts/carrentaltest_user_schema_creation.sql
  - sudo mysql -u root --password="" < src/test/resources/META-INF.scripts/carrentaltest_table_creation.sql

script:
  #  command below runs SonarCloud code coverage analysis,
  #  see: https://steinar.bang.priv.no/2020/03/30/how-to-get-test-coverage-back-in-sonarcloud-maven-builds/
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=Reggy93_company-car-reservation-spring-app